# For comparison of results across all methods
# Code generated by Claude, use with caution

# PLEASE check everhything column has a value before sending it over
# =============================================================================
#  SAVE COMPLETE SUMMARY BUNDLE  (precompute + save + verify)
#  Run this in the file where the models/surfaces live, at the very end.
#  Produces one pickle a teammate can use to draw EVERY comparison plot
#  (RMSE, residuals, butterfly, calendar, P&L) with no access to the models.
#
#  Requires in memory: df, results, TICKER, DRIVE, and the surface functions
#  SURFACES = {"SVI": svi_surface_w, "Vanilla NN": vanilla_w, "Deep Smoothing": deep_w}
#  (optional: arb, pnl, MONEY, hedge_stats — included if present)
# =============================================================================
import pickle, os, numpy as np
os.makedirs(DRIVE, exist_ok=True)

# make sure SURFACES exists (define it if the notebook hasn't yet)
if "SURFACES" not in dir():
    SURFACES = {"SVI": svi_surface_w, "Vanilla NN": vanilla_w, "Deep Smoothing": deep_w}

# ---- 1) PRECOMPUTE the arbitrage curves (needs the live surfaces) -----------
# butterfly g(k) on a representative held-out day / busiest expiry
_day = df[df["is_holdout"]]["quote_date"].max()
_sl  = df[df["quote_date"] == _day]
_exp = _sl["expire_date"].value_counts().idxmax()
_sl  = _sl[_sl["expire_date"] == _exp]
_tau_g = float(_sl["tau"].iloc[0])
_kline = np.linspace(_sl["log_moneyness"].min(), _sl["log_moneyness"].max(), 120)

def _g(wf, k, tau, eps=1e-3):
    tv = np.full_like(k, tau, float); w = wf(k, tv)
    wk  = (wf(k+eps,tv) - wf(k-eps,tv)) / (2*eps)
    wkk = (wf(k+eps,tv) - 2*w + wf(k-eps,tv)) / eps**2
    return (1 - k*wk/(2*w))**2 - (wk/4)*(1/w + 0.25) + wkk/2

# calendar: total variance across maturities at fixed k
_tau_fine = np.linspace(df["tau"].min(), df["tau"].max(), 60)
_k_fixed  = np.linspace(df["log_moneyness"].min(), df["log_moneyness"].max(), 9)

g_bundle   = {"kline": _kline, "tau_g": _tau_g, "day": str(_day.date()), "g": {}}
cal_bundle = {"tau_fine": _tau_fine, "k_fixed": _k_fixed, "lines": {}}
for _name, _wf in SURFACES.items():
    g_bundle["g"][_name]        = _g(_wf, _kline, _tau_g)
    cal_bundle["lines"][_name]  = np.array([_wf(np.full_like(_tau_fine, k0), _tau_fine)
                                            for k0 in _k_fixed])

# ---- 2) ASSEMBLE the bundle -------------------------------------------------
summary_bundle = {
    "ticker":  TICKER,
    "methods": ["Vanilla NN", "SVI", "Deep Smoothing"],

    # held-out predictions -> scatter / residuals / RMSE-by-region / per-date
    "hold": df[df["is_holdout"]][
        ["quote_date","expire_date","dte","tau","log_moneyness","iv",
         "iv_vanilla","iv_svi","iv_deep"]
    ].reset_index(drop=True),

    # scalar metrics -> comparison table + bar charts
    "rmse": {m: float(results[m]) for m in results},
    "arb":  arb if "arb" in dir() else {},

    # arbitrage curves -> butterfly + calendar plots (no surfaces needed)
    "g_curve":   g_bundle,
    "cal_curve": cal_bundle,

    # hedging P&L -> histogram + tail table (if the hedge was run)
    "pnl":         {f"{n}|{m}": np.asarray(pnl[(n,m)]) for (n,m) in pnl} if "pnl" in dir() else {},
    "money":       MONEY if "MONEY" in dir() else [],
    "hedge_stats": hedge_stats if "hedge_stats" in dir() else {},
}

# ---- 3) SAVE + VERIFY (shows what's real vs silently empty) ------------------
path = f"{DRIVE}/summary_bundle_{TICKER}.pkl"
pickle.dump(summary_bundle, open(path, "wb"))

print("saved:", path)
print(f"  hold rows   : {len(summary_bundle['hold'])}")
print(f"  rmse        : {summary_bundle['rmse']}")
print(f"  arb         : {'OK' if summary_bundle['arb'] else 'EMPTY  (run the arbitrage-count cell)'}")
print(f"  g_curve     : {'OK' if summary_bundle['g_curve']['g'] else 'EMPTY'}")
print(f"  cal_curve   : {'OK' if summary_bundle['cal_curve']['lines'] else 'EMPTY'}")
print(f"  pnl         : {'OK ('+str(len(summary_bundle['pnl']))+' arrays)' if summary_bundle['pnl'] else 'EMPTY  (run the hedge cell)'}")

